# HTML Parsig : Parsing a particular campaigns page

In [1]:
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
with open("C:/Users/ASUS/OneDrive/Desktop/Web Scraping/04_Campaigns-Scrape/data/page3.html", "r", encoding="utf-8") as f:
    one_html = f.read()

In [3]:
one_html

'<!DOCTYPE html><html translate="no"><head><script id="_pusher_script_1" src="https://stats.pusher.com/timeline/v2/jsonp/1?session=MjMwMjE2NTY5&amp;bundle=MQ%3D%3D&amp;key=YzAzNTY2MTljYjliNjc4NjZkMGU%3D&amp;lib=anM%3D&amp;version=NC40LjA%3D&amp;cluster=ZXU%3D&amp;features=WyJ3cyJd&amp;timeline=W3siaW5zdGFuY2VzIjoxLCJ0aW1lc3RhbXAiOjE3Nzc3NjcxOTg2NjF9LHsic3RhdGUiOiJjb25uZWN0aW5nIiwidGltZXN0YW1wIjoxNzc3NzY3MTk4NjYxfSx7ImNpZCI6MSwidHJhbnNwb3J0Ijoid3NzIiwidGltZXN0YW1wIjoxNzc3NzY3MTk4NjYyfSx7ImNpZCI6MSwic3RhdGUiOiJpbml0aWFsaXplZCIsInRpbWVzdGFtcCI6MTc3Nzc2NzE5ODY2Mn0seyJjaWQiOjEsInN0YXRlIjoiY29ubmVjdGluZyIsInRpbWVzdGFtcCI6MTc3Nzc2NzE5ODY2Nn0seyJjaWQiOjEsInN0YXRlIjoib3BlbiIsInRpbWVzdGFtcCI6MTc3Nzc2NzE5OTU3OX0seyJzdGF0ZSI6ImNvbm5lY3RlZCIsInBhcmFtcyI6eyJzb2NrZXRfaWQiOiIyNjc3MzUuMjg5NTc2MCJ9LCJ0aW1lc3RhbXAiOjE3Nzc3NjcxOTk2NDd9XQ%3D%3D" type="text/javascript" charset="UTF-8" async=""></script><meta http-equiv="origin-trial" content="3NNj0GXVktLOmVKwWUDendk4Vq2qgMVDBDX+Sni48ATJl9JBj+zF+9W2HGB3pvt6qowOihTbQgTeBm9SKbdTwYAAABfeyJvcmlnaW4iOiJodHRwczovL3JlY2FwdGNoYS5uZXQ6NDQzIiwiZmVhdHVyZSI6IlRwY2QiLCJleHBpcnkiOjE3MzUzNDM5OTksImlzVGhpcmRQYXJ0eSI6dHJ1ZX0="><meta http-equiv="origin-trial" content="A6iYDRdcg1LVww9DNZEU+JUx2g1IJxSxk4P6F+LimR0ElFa38FydBqtz/AmsKdGr11ZooRgDPCInHJfGzwtR+A4AAACXeyJvcmlnaW4iOiJodHRwczovL3d3dy5yZWNhcHRjaGEubmV0OjQ0MyIsImZlYXR1cmUiOiJEaXNhYmxlVGhpcmRQYXJ0eVN0b3JhZ2VQYXJ0aXRpb25pbmczIiwiZXhwaXJ5IjoxNzU3OTgwODAwLCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ==">\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n    <meta name="google" content="notranslate">\n    <link rel="preconnect" href="https://challenges.cloudflare.com">\n    <title>The Friendship Circle 2026 - Charity Extra</title>\n\n    <script type="text/javascript" async="" charset="utf-8" src="https://www.gstatic.com/recaptcha/releases/gTpTIWhbKpxADzTzkcabhXN4/recaptcha__en.js" crossorigin="anonymous" integrity="sha384-H/5bR8BVxoDZIIp1lThXvsuAj/gHvImPQ0kayVpCevmOrRalo0FwJubK3EoX8w37"></script><script src="https://js.stripe.com/v3" crossorigin="anonymous"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js" crossorigin="anonymous"></script>\n\n    <script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async="" defer=""></script>\n        <link async="" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;display=swap" rel="stylesheet">\n        <link async="" href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400i,600i,700i&amp;display=swap" rel="stylesheet">\n        <link href="https://cdn.charityextra.com/lib/bootstrap/css/bootstrap.css" rel="stylesheet">\n    <link href="https://cdn.charityextra.com/css/public/fire.css" rel="stylesheet">\n    <link href="https://cdn.charityextra.com/css/public/confetti.css?64" rel="stylesheet">\n\n    <link href="https://cdn.charityextra.com/css/public/user.css?67" rel="stylesheet">\n    <script src="https://cdn.charityextra.com/js/public/user.js?67" crossorigin="anonymous"></script>\n    <link href="/assets/css/friendshipcircle.css?67" rel="stylesheet">\n    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css">\n\n    <script>\n\n        function readCookie(name) {\n            var nameEQ = name + "=";\n            var ca = document.cookie.split(\';\');\n            for (var i = 0; i < ca.length; i++) {\n                var c = ca[i];\n                while (c.charAt(0) == \' \') c = c.substring(1, c.length);\n                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);\n            }\n            return null;\n        }\n\n\n\n\n    </script>\n    <!-- Google tag (gtag.js) -->\n<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4JEVP9DEKL"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n  gtag(\'consent\', \'default\', {\n      ad_storage: \'denied\',\n      analytics_storage: \'denied\',\n      functionality_storage: \'denied\',\n      personalization_storage: \'denied\',\n      security_storage: \'denied\'\n    });\n  gtag(\'config\', \'G-4JEVP9DEKL\',{\n      client_storage: \'none\'\n    });\n</script>\n\n\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>\n    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.css" rel="stylesheet">\n    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>\n\n    <link href="https://cdn.charityextra.com/lib/fancybox/jquery.fancybox-user.css" rel="stylesheet">\n    <script src="https://cdn.charityextra.com/lib/fancybox/jquery.fancybox.js" crossorigin="anonymous"></script>\n\n    <script src="https://cdn.charityextra.com/assets/js/confetti.browser.min.js"></script>\n        <script src="https://www.recaptcha.net/recaptcha/api.js?render=6LfJ5OwUAAAAANEMDFkVHUeBADwtlhSjrgtn-DWS"></script>\n    <style>\n        select.select-currency { font-size: 25px; }\n        .grecaptcha-badge { visibility: collapse !important; }\n        div.time-block { margin-top: 0px !important }\n        div#remaining-time-holder > span { margin: 0; position: absolute; top: 50%; -ms-transform: translateY(-50%); transform: translateY(-50%); }\n        .selected-team-modal { border: 1px solid #36100D; border-top: 1px solid white; margin-top: -1px; position: relative; background: white; }\n\n        .team-description { overflow: hidden }\n\n        .fix-to-bottom-card { }\n\n        .text-right-imp {\n            text-align: right !important\n        }\n\n\n        .team-description.mini { max-height: 130px; text-overflow: ellipsis; overflow: hidden; }\n\n        .team-description.very-mini { max-height: 60px; text-overflow: ellipsis; overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3; }\n\n        .team-name-holder { position: relative; }\n\n        .team-read-expand { cursor: pointer; display: flex; justify-content: center; align-items: flex-end; height: 5em; bottom: 0; width: 100%; position: absolute; background: #fff; background: var(--team-color,#fff); background: linear-gradient(0deg,#fff 60%,transparent); background: linear-gradient(0deg,var(--team-color,#fff) 60%,transparent); color: #0683b3; }\n\n        .multiselect__content-wrapper {\n            overflow-x: hidden!important;\n        }\n\n        .receipt-country-holder{margin: -.5rem 0.25rem 1rem 0.25rem;padding: 0.5rem;border-radius: 0.25rem;border: #bee5eb 1px solid;}\n    </style>\n    <script>\n\n        var celebrateGoalRunning = false;\n        var celebrateGoalCount = 0;\n\n        function celebrateGoalReset() {\n            celebrateGoalRunning = false;\n            celebrateGoalCount = 0;\n        }\n\n        function celebrateGoal() {\n            var count = 200;\n\n\n            function fire(particleRatio, opts) {\n\n                function getRandomArbitrary(min, max) {\n                    return Math.random() * (max - min) + min;\n                }\n\n                var defaults = {\n                    origin: {\n                        x: Math.random(),\n                        y: getRandomArbitrary(0.6, 1)\n                    },\n                    zIndex: 0\n                };\n\n\n\n                confetti(Object.assign({}, defaults, opts, {\n                    particleCount: Math.floor(count * particleRatio)\n                }));\n            }\n\n            fire(0.25, {\n                spread: 70,\n                startVelocity: 55,\n            });\n            fire(0.2, {\n                spread: 80,\n            });\n            fire(0.35, {\n                spread: 100,\n                decay: 0.91,\n                scalar: 0.8\n            });\n            fire(0.1, {\n                spread: 120,\n                startVelocity: 25,\n                decay: 0.92,\n                scalar: 1.2\n            });\n            fire(0.1, {\n                spread: 120,\n                startVelocity: 45,\n            });\n\n            celebrateGoalCount += 1;\n            if (celebrateGoalCount < 60) {\n                window.setTimeout(function () { celebrateGoal() }, 800);\n            }\n        }\n\n        function celebrateComplete() {\n            confetti.reset();\n            var duration = (60 * 1000) * 3;\n            var animationEnd = Date.now() + duration;\n            var defaults = { startVelocity: 30, spread: 360, ticks: 60, zIndex: 0 };\n\n            function randomInRange(min, max) {\n                return Math.random() * (max - min) + min;\n            }\n\n            var interval = setInterval(function () {\n                var timeLeft = animationEnd - Date.now();\n\n                if (timeLeft <= 0) {\n                    return clearInterval(interval);\n                }\n\n                var particleCount = 50 * (timeLeft / duration);\n                // since particles fall down, start a bit higher than random\n                confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 } }));\n                confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.3, 0.5), y: Math.random() - 0.2 } }));\n                confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.5, 0.7), y: Math.random() - 0.2 } }));\n                confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 } }));\n            }, 250);\n        }\n\n        function checkIE() {\n            var ua = window.navigator.userAgent;\n            var msie = ua.indexOf("MSIE ");\n\n            if (msie > -1 || !!navigator.userAgent.match(/Trident.*rv\\:11\\./)) {\n                alert(\'Internet Explorer is unsupported, Please use Chrome, FireFox, Edge or Safari\');\n            }\n        }\n        checkIE();\n\n        function animatethis(targetElement, speed) {\n            var scrollWidth = $(targetElement).get(0).scrollWidth;\n            var clientWidth = $(targetElement).get(0).clientWidth;\n            var runScroll = true;\n            $(targetElement).scroll(function () {\n                runScroll = false;\n            });\n            $(targetElement).animate({ scrollLeft: scrollWidth - clientWidth },\n                {\n                    duration: speed,\n                    complete: function () {\n                        if (runScroll)\n                            targetElement.animate({ scrollLeft: 0 },\n                                {\n                                    duration: speed,\n                                    complete: function () {\n                                        if (runScroll)\n                                            animatethis(targetElement, speed);\n                                    }\n                                });\n                    }\n                });\n        };\n    </script>\n\n\n    \n\n    <meta property="og:image" itemprop="image" content="https://cdn.charityextra.com/campaign-assets/friendshipcircle/logo-image-8muho.png">\n    <meta property="og:type" content="website">\n    <meta property="og:url" content="https://www.charityextra.com/friendshipcircle">\n    <meta property="og:title" content="The Friendship Circle 2026">\n\n    <script src="https://cdn.charityextra.com/js/public/vue-multiselect.min.js" crossorigin="anonymous"></script>\n    <link rel="stylesheet" href="https://cdn.charityextra.com/css/public/vue-multiselect.min.css">\n\n        <script src="https://cdn.charityextra.com/lib/vue-select/vue-select.js" crossorigin="anonymous"></script>\n        <link rel="stylesheet" href="https://cdn.charityextra.com/lib/vue-select/vue-select.css">\n\n\n    <script src="https://cdn.charityextra.com/js/public/tween.js" crossorigin="anonymous"></script>\n    <style>\n        \n    </style>\n    <style>\n\n        .post-image{\n            padding: 0.25rem;\n            background-color: #fff;\n            border: 1px solid #dee2e6;\n            border-radius: 0.25rem;\n            max-width: 100%;\n            height: auto;\n        }\n\n        .social-widget {\n            height: 450px !important;\n        }\n\n        .team-split-item {\n            border-bottom: 1px solid #562A90;\n            padding-bottom: 10px;\n            padding: 1px 8px;\n        }\n\n        .team-split-item-alternate {\n            background-color: #eceaea;\n        }\n\n        .tooltip.show {\n            z-index: 9999999999\n        }\n\n        .ccicon {\n            height: 23px;\n            position: absolute;\n            right: 6px;\n            z-index: 999 !important;\n            opacity: 0.7;\n            margin-top: 10px;\n            padding-right: 15px;\n        }\n\n        .credit-card-field {\n            margin-top: 3px;\n            font-size: 16px;\n            width: 100%;\n            box-sizing: border-box;\n            z-index: 10;\n        }\n\n        .vs__clear {\n            display: none\n        }\n\n        .vs__open-indicator {\n            margin: 0.5rem;\n        }\n\n        .vs__dropdown-toggle {\n            border-radius: 0px;\n            border-color: #562A90;\n        }\n\n        .vs__search {\n            height: calc(1.5em + 0.75rem + 2px);\n            line-height: 1.5;\n            font-size: 1rem;\n        }\n\n        .vs--single.vs--open .vs__selected {\n            position: unset\n        }\n\n        iframe.cardknox-holder {\n            border: 0 solid black;\n            width: 100%;\n            height: 45px;\n            padding: 0px;\n            margin-bottom: 5px;\n        }\n\n        .pege-header {\n            padding-left: 112px;\n            font-size: 25px;\n            color: #562A90;\n            font-weight: 600;\n            position: absolute;\n            top: 13px;\n            color: #3F51B5\n        }\n\n        .home-multi-message {\n            font-weight: 600;\n            font-size: 15px;\n            color: #562A90;\n            text-transform: none;\n            text-align: right\n        }\n\n        .play-button {\n            background-color: #562A90 B3;\n            padding: 5px;\n            border-radius: 50%;\n        }\n\n        .upPaymentCardContainer {\n            height: 37px;\n            max-height: 37px;\n            padding: 6px;\n            border: 1px solid #562A90;\n        }\n\n        .btn-primary-donate {\n            border-color: transparent;\n            background-color: #562A90 !important;\n            color: white;\n        }\n\n        .btn-secondary-donate {\n            border-color: transparent;\n            background-color: #562A90 !important;\n            color: white;\n        }\n\n        input.form-control:focus {\n            box-shadow: none !important\n        }\n\n        span.enter-amount-mock {\n            border: 0px;\n            font-size: 2.5rem;\n            width: calc(100% - 90px);\n            font-weight: 400;\n            text-align: right;\n            color: #9E9E9E;\n            display: inline-block;\n            direction: ltr;\n            line-height: 2.5rem;\n        }\n\n        @-webkit-keyframes theme_change {\n            from {\n                color: #562A90;\n            }\n\n            to {\n                color: #FB9116;\n            }\n        }\n\n        @-moz-keyframes theme_change {\n            from {\n                color: #562A90;\n            }\n\n            to {\n                color: #FB9116;\n            }\n        }\n\n        @-ms-keyframes theme_change {\n            from {\n                color: #562A90;\n            }\n\n            to {\n                color: #FB9116;\n            }\n        }\n\n        @-o-keyframes theme_change {\n            from {\n                color: #562A90;\n            }\n\n            to {\n                color: #FB9116;\n            }\n        }\n\n        @keyframes theme_change {\n            from {\n                color: #562A90;\n            }\n\n            to {\n                color: #FB9116;\n            }\n        }\n\n        @-webkit-keyframes word_redding {\n            from {\n                color: #e28989;\n            }\n\n            to {\n                color: #b62c2c;\n            }\n        }\n\n        @-moz-keyframes word_redding {\n            from {\n                color: #e28989;\n            }\n\n            to {\n                color: #b62c2c;\n            }\n        }\n\n        @-ms-keyframes word_redding {\n            from {\n                color: #e28989;\n            }\n\n            to {\n                color: #b62c2c;\n            }\n        }\n\n        @-o-keyframes word_redding {\n            from {\n                color: #e28989;\n            }\n\n            to {\n                color: #b62c2c;\n            }\n        }\n\n        @keyframes word_redding {\n            from {\n                color: #e28989;\n            }\n\n            to {\n                color: #b62c2c;\n            }\n        }\n\n        @keyframes shake {\n            1%, 9% {\n                transform: translate3d(-1px, 0, 0);\n            }\n\n            2%, 8% {\n                transform: translate3d(2px, 0, 0);\n            }\n\n            3%, 5%, 7% {\n                transform: translate3d(-4px, 0, 0);\n            }\n\n            4%, 6% {\n                transform: translate3d(4px, 0, 0);\n            }\n\n            10%, 100% {\n                transform: translate3d(0, 0, 0);\n            }\n        }\n\n\n        .trophy-anim {\n            animation: theme_change 1s infinite alternate;\n        }\n\n        .trophy-anim-fast {\n            animation: word_redding .5s infinite alternate;\n        }\n\n        .trophy-anim-shake {\n            animation: shake 5s infinite cubic-bezier(.36,.07,.19,.97) both;\n            transform: translate3d(0, 0, 0);\n            backface-visibility: hidden;\n            perspective: 1000px;\n        }\n\n        ::-webkit-scrollbar {\n            width: 0.7em;\n            height: 1em\n        }\n\n        ::-webkit-scrollbar-button {\n            background: #562A90\n        }\n\n        ::-webkit-scrollbar-track-piece {\n            background: #eee\n        }\n\n        ::-webkit-scrollbar-thumb {\n            background: #FB9116\n        }\n\n        toast toast-info {\n            padding-left: 15px !important;\n            width: 270px\n        }\n\n        #toast-container > .toast {\n            background-image: none !important;\n        }\n\n        iframe#live-stream-iframe {\n            width: 100%;\n            margin-top: 25px;\n            border-radius: 13px;\n        }\n\n        @media (min-width: 900px) {\n            #donate-form .modal-dialog {\n                max-width: 750px;\n            }\n\n            .right-side-image {\n                height: 419px\n            }\n        }\n\n        @media (max-width: 899px) {\n            .right-side-image {\n                margin-top: 10px\n            }\n        }\n\n        .btn-accordion:after {\n            content: "\\f107";\n            font-family: \'Font Awesome 5 Free\';\n            font-weight: 900;\n            float: right;\n        }\n\n        .btn-accordion.collapsed:after {\n            content: "\\f105";\n        }\n\n        .team-top-link {\n            border: 2px solid #FB9116;\n            border-radius: 7px;\n            padding: 0px 5px 5px 5px;\n            cursor: pointer;\n            display: inline-block;\n            background-color: #FB9116 33\n        }\

In [4]:
one_soup = BeautifulSoup(one_html, 'html.parser')

In [5]:
#campaign_name
one_soup.find("h5").get_text(strip=True)

'The Friendship Circle'

In [6]:
# amount_raised
one_soup.select_one("div.raised-figs.ext").get_text(strip=True)

'£445,065'

In [ ]:
#target_amount
one_soup.select_one("div.raised-of-primary div.number-holder").get_text(strip=True)

'£ 450,000'

In [8]:
#associated emails/ phone numbers
one_soup.select_one("div.row.mid-donate.mt-3 > div").get_text()

'Campaign email: sarah@friendshipcircle.co.uk Campaign number: 0161 501 1792'

In [9]:
# number of donors
one_soup.select_one("label#label-donors").get_text()

'3143 Donors'

## Loading all html files and parsing them

In [14]:
data = []

# function for handling error in emplty page cases
def safe_text(tag, default=""):
    return tag.get_text(strip=True) if tag else default


for i in range(29):
    with open(f"C:/Users/ASUS/OneDrive/Desktop/Web Scraping/04_Campaigns-Scrape/data/page_number{i}.html", "r", encoding="utf-8") as f:
        html = f.read()
    soup = BeautifulSoup(html, 'html.parser')
    data.append({
        "campaign_name" : safe_text(soup.find("h5")),

        "target_amount" : safe_text(soup.select_one("div.raised-of-primary div.number-holder")),

        "amount_raised" : safe_text(soup.select_one("div.raised-figs")),

        "number_of_donors" : safe_text(soup.select_one("label#label-donors")),

        "emails_or_phone" : safe_text(soup.select_one("div.row.mid-donate.mt-3 > div"))        
        
    })

In [15]:
data

[{'campaign_name': 'Torah Temimah Primary School',
  'target_amount': '£ 400,000',
  'amount_raised': '£385,348',
  'number_of_donors': '3065Donors',
  'emails_or_phone': 'Campaign email: ttpscampaign@gmail.com'},
 {'campaign_name': 'Jewish future in this country is inseparable from Britain’s destiny.',
  'target_amount': '£ 500,000',
  'amount_raised': '£38,177',
  'number_of_donors': '183Donors',
  'emails_or_phone': 'Create my fundraising team page'},
 {'campaign_name': 'The Friendship Circle',
  'target_amount': '£ 450,000',
  'amount_raised': '£445,065',
  'number_of_donors': '3143Donors',
  'emails_or_phone': 'Campaign email: sarah@friendshipcircle.co.uk Campaign number: 0161 501 1792'},
 {'campaign_name': '9 YESOMIM',
  'target_amount': '£ 600,000',
  'amount_raised': '£533,030',
  'number_of_donors': '3234Donors',
  'emails_or_phone': '9Yesomim@gmail.com'},
 {'campaign_name': 'WIZOuk',
  'target_amount': '£ 25,000',
  'amount_raised': '£6,197',
  'number_of_donors': '114Donors',
  'emails_or_phone': 'Campaign email: emma@wizouk.org'},
 {'campaign_name': 'Golders Green Kollel',
  'target_amount': '£ 400,000',
  'amount_raised': '£420,577',
  'number_of_donors': '1292Donors',
  'emails_or_phone': 'Campaign email: golders.green.kolel@gmail.com'},
 {'campaign_name': 'Connections that Count',
  'target_amount': '£ 360,000',
  'amount_raised': '£296,257',
  'number_of_donors': '7025Donors',
  'emails_or_phone': 'Create my fundraising team page'},
 {'campaign_name': 'Talmud Torah Tiferes Shlomo',
  'target_amount': '£ 425,000',
  'amount_raised': '£423,730',
  'number_of_donors': '3377Donors',
  'emails_or_phone': 'Campaign email: tttscampaign@gmail.com'},
 {'campaign_name': 'Chabad Buckhurst Hill',
  'target_amount': '£ 100,000',
  'amount_raised': '£107,080',
  'number_of_donors': '474Donors',
  'emails_or_phone': 'Campaign email: rabbibrandman@chabadonthehill.co.uk'},
 {'campaign_name': 'Our Responsibility',
  'target_amount': '£ 650,000',
  'amount_raised': '£629,681',
  'number_of_donors': '4945Donors',
  'emails_or_phone': 'Campaign email: ourresponsibility21@gmail.com'},
 {'campaign_name': 'Secure Premises Appeal',
  'target_amount': '£ 5,000,000',
  'amount_raised': '£1,884,338',
  'number_of_donors': '8136Donors',
  'emails_or_phone': 'Create my fundraising team page'},
 {'campaign_name': 'Heimishe Kitchen - Care & Share',
  'target_amount': '£ 200,000',
  'amount_raised': '£169,874',
  'number_of_donors': '1571Donors',
  'emails_or_phone': "To all our friends and the wider community. Due to the terrible attack on our community's Hatzola Ambulances, and the subsequent important campaign to raise funds for Hatzola - we have decided to extend our campaign by a week to give breathing space to Hatzola's emergency appeal. Wishing all the community only good news !Campaign email: \ttheheimishekitchen@gmail.com Helpline: 0203 746 3420"},
 {'campaign_name': 'Emergency Appeal - Families of Arad',
  'target_amount': '£ 400,000',
  'amount_raised': '£248,884',
  'number_of_donors': '1214Donors',
  'emails_or_phone': 'Create my fundraising team page'},
 {'campaign_name': "Leman HaTorah V'Lomdeoh - למען התורה ולומדיה",
  'target_amount': '£ 1,000,000',
  'amount_raised': '£942,795',
  'number_of_donors': '5577Donors',
  'emails_or_phone': 'Campaign Email: events@yst613.co.ukCampaign Hotline Number: +44 161 738 1213UK Account Name: Shaarei Torah Trust - Account No: 08325480  Sort Code: 53-81-36IBAN: GB47 NWBK 5381 3608 3254 80EUROPE - Euro Account Number: 86382782 - Sort Code: \xa0 30-95-42 BIC: LOYDGB21004 - IBAN: GB27LOYD30954286382782SWITZERLAND: Call for detailsUSA - Account name: SHAAREI TORAH - Account number: 140/01/06176348 - Account type: International Account  - Currency: USDBIC: NWBKGB2L - IBAN: GB29NWBK60730106176348'},
 {'campaign_name': 'Hatzola Edgware',
  'target_amount': '',
  'amount_raised': '£67,096',
  'number_of_donors': '627Donors',
  'emails_or_phone': 'Create my fundraising team page'},
 {'campaign_name': 'One Yeshiva. Global Impact',
  'target_amount': '£ 4,500,000',
  'amount_raised': '£4,338,877',
  'number_of_donors': '14555Donors',
  'emails_or_phone': 'Campaign email: campaign@gyalumni.orgCampaign numbers - UK: +447307212342 - USA: +17329367940 - Text or call to donate and for updates.Israel: +97239125681 - Call to donate and for updates - For SEIF 46 donations, see "Bank Details" below.Create my fundraising team page'},
 {'campaign_name': "The Snow Slowed Us. It Didn't Stop Us.",
  'target_amount': '$ 750,000',
  'amount_raised': '$553,830',
  'number_of_donors': '1742Donors',
  'emails_or_phone': 'Snow Extension. Same Goal.'},
 {'campaign_name': 'Keren Olam Hatorah',
  'target_amount': '',
  'amount_raised': '£7,862,438Total Raised',
  'number_of_donors': '',
  'emails_or_phone': 'For enquiries and to fulfill pledges please email: info@kerenolamhatorah.org'},
 {'campaign_name': '',
  'target_amount': '',
  'amount_raised': '',
  'number_of_donors': '',
  'emails_or_phone': ''},
 {'campaign_name': 'If you would like to join our teams, please fill your details below:',
  'target_amount': '',
  'amount_raised': '',
  'number_of_donors': '',
  'emails_or_phone': ''},
 {'campaign_name': 'BIKE4KEF 2026',
  'target_amount': '',
  'amount_raised': '£19Total Raised',
  'number_of_donors': '3Donors',
  'emails_or_phone': 'JOIN BIKE4KEF 2026'},
 {'campaign_name': 'Chai Lifeline Belgium',
  'target_amount': '',
  'amount_raised': '€0',
  'number_of_donors': '0Donors',
  'emails_or_phone': 'JOIN RIDE4CHAI 2026'},
 {'campaign_name': 'Side By Side',
  'target_amount': '£ 350,000',
  'amount_raised': '£14,876',
  'number_of_donors': '470Donors',
  'emails_or_phone': 'Campaign email: campaign@sidebyside.org.uk'},
 {'campaign_name': 'Byachad',
  'target_amount': '£ 50,000',
  'amount_raised': '£46,651',
  'number_of_donors': '1290Donors',
  'emails_or_phone': 'Campaign email: info@rayzemore.com'},
 {'campaign_name': 'Howell Mikvah',
  'target_amount': '$ 600,000',
  'amount_raised': '$250,712',
  'number_of_donors': '1227Donors',
  'emails_or_phone': 'Campaign email: mikvahofhowell@gmail.com'},
 {'campaign_name': 'Yad Voezer - Special Forever',
  'target_amount': '',
  'amount_raised': '£2,000Total Raised',
  'number_of_donors': '2Donors',
  'emails_or_phone': ''},
 {'campaign_name': 'Beis Chaya Rochel',
  'target_amount': '£ 200,000',
  'amount_raised': '£11,473',
  'number_of_donors': '131Donors',
  'emails_or_phone': 'Campaign email: walk@bcrsem.org.uk'},
 {'campaign_name': 'If you would like to join our teams, please fill your details below:',
  'target_amount': '',
  'amount_raised': '',
  'number_of_donors': '',
  'emails_or_phone': ''},
 {'campaign_name': 'If you would like to join our teams, please fill your details below:',
  'target_amount': '',
  'amount_raised': '',
  'number_of_donors': '',
  'emails_or_phone': ''}]

In [16]:
pd.DataFrame(data)

,campaign_name,target_amount,amount_raised,number_of_donors,emails_or_phone
0,Torah Temimah Primary School,"£ 400,000","£385,348",3065Donors,Campaign email: ttpscampaign@gmail.com
1,Jewish future in this country is inseparable f...,"£ 500,000","£38,177",183Donors,Create my fundraising team page
2,The Friendship Circle,"£ 450,000","£445,065",3143Donors,Campaign email: sarah@friendshipcircle.co.uk C...
3,9 YESOMIM,"£ 600,000","£533,030",3234Donors,9Yesomim@gmail.com
4,WIZOuk,"£ 25,000","£6,197",114Donors,Campaign email: emma@wizouk.org
5,Golders Green Kollel,"£ 400,000","£420,577",1292Donors,Campaign email: golders.green.kolel@gmail.com
6,Connections that Count,"£ 360,000","£296,257",7025Donors,Create my fundraising team page
7,Talmud Torah Tiferes Shlomo,"£ 425,000","£423,730",3377Donors,Campaign email: tttscampaign@gmail.com
8,Chabad Buckhurst Hill,"£ 100,000","£107,080",474Donors,Campaign email: rabbibrandman@chabadonthehill....
9,Our Responsibility,"£ 650,000","£629,681",4945Donors,Campaign email: ourresponsibility21@gmail.com
10,Secure Premises Appeal,"£ 5,000,000","£1,884,338",8136Donors,Create my fundraising team page
11,Heimishe Kitchen - Care & Share,"£ 200,000","£169,874",1571Donors,To all our friends and the wider community. Du...
12,Emergency Appeal - Families of Arad,"£ 400,000","£248,884",1214Donors,Create my fundraising team page
13,Leman HaTorah V'Lomdeoh - למען התורה ולומדיה,"£ 1,000,000","£942,795",5577Donors,Campaign Email: events@yst613.co.ukCampaign Ho...
14,Hatzola Edgware,,"£67,096",627Donors,Create my fundraising team page
15,One Yeshiva. Global Impact,"£ 4,500,000","£4,338,877",14555Donors,Campaign email: campaign@gyalumni.orgCampaign ...
16,The Snow Slowed Us. It Didn't Stop Us.,"$ 750,000","$553,830",1742Donors,Snow Extension. Same Goal.
17,Keren Olam Hatorah,,"£7,862,438Total Raised",,For enquiries and to fulfill pledges please em...
18,,,,,
19,"If you would like to join our teams, please fi...",,,,
20,BIKE4KEF 2026,,£19Total Raised,3Donors,JOIN BIKE4KEF 2026
21,Chai Lifeline Belgium,,€0,0Donors,JOIN RIDE4CHAI 2026
22,Side By Side,"£ 350,000","£14,876",470Donors,Campaign email: campaign@sidebyside.org.uk
23,Byachad,"£ 50,000","£46,651",1290Donors,Campaign email: info@rayzemore.com
24,Howell Mikvah,"$ 600,000","$250,712",1227Donors,Campaign email: mikvahofhowell@gmail.com
25,Yad Voezer - Special Forever,,"£2,000Total Raised",2Donors,
26,Beis Chaya Rochel,"£ 200,000","£11,473",131Donors,Campaign email: walk@bcrsem.org.uk
27,"If you would like to join our teams, please fi...",,,,
28,"If you would like to join our teams, please fi...",,,,

In [17]:
df = pd.DataFrame(data)

In [27]:
df["number_of_donors"].str.replace("Donors", "")

0      3065
1       183
2      3143
3      3234
4       114
5      1292
6      7025
7      3377
8       474
9      4945
10     8136
11     1571
12     1214
13     5577
14      627
15    14555
16     1742
17
18
19
20        3
21        0
22      470
23     1290
24     1227
25        2
26      131
27
28
Name: number_of_donors, dtype: object

In [26]:
import re
df["number_of_donors"].str.extract(r"(\d+)\s*donors", flags=re.IGNORECASE)

        0
0    3065
1     183
2    3143
3    3234
4     114
5    1292
6    7025
7    3377
8     474
9    4945
10   8136
11   1571
12   1214
13   5577
14    627
15  14555
16   1742
17    NaN
18    NaN
19    NaN
20      3
21      0
22    470
23   1290
24   1227
25      2
26    131
27    NaN
28    NaN

In [28]:
df["number_of_donors"] = df["number_of_donors"].str.extract(r"(\d+)\s*donors", flags=re.IGNORECASE)

In [30]:
df.head()

,campaign_name,target_amount,amount_raised,number_of_donors,emails_or_phone
0,Torah Temimah Primary School,"£ 400,000","£385,348",3065,Campaign email: ttpscampaign@gmail.com
1,Jewish future in this country is inseparable f...,"£ 500,000","£38,177",183,Create my fundraising team page
2,The Friendship Circle,"£ 450,000","£445,065",3143,Campaign email: sarah@friendshipcircle.co.uk C...
3,9 YESOMIM,"£ 600,000","£533,030",3234,9Yesomim@gmail.com
4,WIZOuk,"£ 25,000","£6,197",114,Campaign email: emma@wizouk.org

In [44]:
df["amount_raised"].replace(r"[a-zA-Z]+", "", regex=True)

0        £385,348
1         £38,177
2        £445,065
3        £533,030
4          £6,197
5        £420,577
6        £296,257
7        £423,730
8        £107,080
9        £629,681
10     £1,884,338
11       £169,874
12       £248,884
13       £942,795
14        £67,096
15     £4,338,877
16       $553,830
17    £7,862,438
18
19
20           £19
21             €0
22        £14,876
23        £46,651
24       $250,712
25        £2,000
26        £11,473
27
28
Name: amount_raised, dtype: object

In [45]:
df["amount_raised"] = df["amount_raised"].replace(r"[a-zA-Z]+", "", regex=True)

In [46]:
df.head()

,campaign_name,target_amount,amount_raised,number_of_donors,emails_or_phone
0,Torah Temimah Primary School,"£ 400,000","£385,348",3065,Campaign email: ttpscampaign@gmail.com
1,Jewish future in this country is inseparable f...,"£ 500,000","£38,177",183,Create my fundraising team page
2,The Friendship Circle,"£ 450,000","£445,065",3143,Campaign email: sarah@friendshipcircle.co.uk C...
3,9 YESOMIM,"£ 600,000","£533,030",3234,9Yesomim@gmail.com
4,WIZOuk,"£ 25,000","£6,197",114,Campaign email: emma@wizouk.org

In [53]:
pd.reset_option('display.max_colwidth')

In [76]:
df["emails_or_phone"].str.findall(r"\S+@\S+").str[0]

0                  ttpscampaign@gmail.com
1                                     NaN
2            sarah@friendshipcircle.co.uk
3                      9Yesomim@gmail.com
4                         emma@wizouk.org
5           golders.green.kolel@gmail.com
6                                     NaN
7                  tttscampaign@gmail.com
8     rabbibrandman@chabadonthehill.co.uk
9           ourresponsibility21@gmail.com
10                                    NaN
11           theheimishekitchen@gmail.com
12                                    NaN
13            events@yst613.co.ukCampaign
14                                    NaN
15          campaign@gyalumni.orgCampaign
16                                    NaN
17              info@kerenolamhatorah.org
18                                    NaN
19                                    NaN
20                                    NaN
21                                    NaN
22             campaign@sidebyside.org.uk
23                     info@rayzemore.com
24               mikvahofhowell@gmail.com
25                                    NaN
26                     walk@bcrsem.org.uk
27                                    NaN
28                                    NaN
Name: emails_or_phone, dtype: object

In [77]:
df["email"] = df["emails_or_phone"].str.findall(r"\S+@\S+").str[0]

In [78]:
df.head()

,campaign_name,target_amount,amount_raised,number_of_donors,emails_or_phone,email
0,Torah Temimah Primary School,"£ 400,000","£385,348",3065,Campaign email: ttpscampaign@gmail.com,ttpscampaign@gmail.com
1,Jewish future in this country is inseparable f...,"£ 500,000","£38,177",183,Create my fundraising team page,NaN
2,The Friendship Circle,"£ 450,000","£445,065",3143,Campaign email: sarah@friendshipcircle.co.uk C...,sarah@friendshipcircle.co.uk
3,9 YESOMIM,"£ 600,000","£533,030",3234,9Yesomim@gmail.com,9Yesomim@gmail.com
4,WIZOuk,"£ 25,000","£6,197",114,Campaign email: emma@wizouk.org,emma@wizouk.org

In [84]:
df.to_csv("C:/Users/ASUS/OneDrive/Desktop/Web Scraping/04_Campaigns-Scrape/data/01_scraped_campaign_data.csv", index=False)